title: ESE 5160 Final Project Demo Website
description: Project Demo site of T10 Web Weaver
theme: slate

# Optional: Social links or additional configs
author: Zhiye Zhang

# Optional: Markdown settings
markdown: kramdown
